### ISSUE TITLE
FileExists error when augmenting midi dataset with tokenize_midi_dataset

### ISSUE THREAD

**Issue by parneyw** [Natooz/MidiTok#107]
Let me start by saying that I really appreciate this project! This is my first time raising an issue in GitHub so apologies if I don't have the proper etiquette.

(Note: In the snippets below I replace the file name with `<file_name>.json` because the actual name was very long.)

I'm getting the following error when I try to run the example code to tokenize a MIDI dataset with augmentation from `README.md`:
```python
tokenizer.tokenize_midi_dataset(midi_paths, Path(out_dir, "tokens_noBPE"),
                                data_augment_offsets=data_augmentation_offsets)
```
results in:
```
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'datasets\\REMI\\maestro-v3.0.0\\tokens_noBPE\\<file_name>.json'
```

I believe this is because the default behaviour of `data_augmentation_dataset` is to copy the original files to `out_dir`, which leads to an attempt to overwrite the original `.json` file.

Apparently the issue is with the `mkdir` call in `data_augmentation.py`:
```
File [c:\Users\...\miditok\data_augmentation\data_augmentation.py:165]
...
    [159]                     ids = ids[0]
    [160]                 saving_path = (
    [161]                     out_path
    [162]                     / file_path.relative_to(data_path)
    [163]                     / f"{file_path.stem}.json"
    [164]                 )
--> [165]                 saving_path.parent.mkdir(parents=True, exist_ok=True)
``` 

So I ran a little test by printing `saving_path` and `saving_path.parent`:
```python
if copy_original_in_new_location and out_path is not None:
    if tokenizer.one_token_stream:
        ids = ids[0]
    saving_path = (
        out_path
        / file_path.relative_to(data_path) # <--------------------- problematic???
        / f"{file_path.stem}.json"
    )
    print(f"{saving_path=} {saving_path.parent=}") # <--------- ADDED THIS LINE FOR DEBUGGING
    saving_path.parent.mkdir(parents=True, exist_ok=True)
```
resulting in:
```
saving_path=WindowsPath('datasets/REMI/maestro-v3.0.0/tokens_noBPE/<file_name>.json/<file_name>.json')
saving_path.parent=WindowsPath('datasets/REMI/maestro-v3.0.0/tokens_noBPE/<file_name>.json')
```

I did further investigation by recreating the scenario manually, where `tokens.json` lives in `mock_datasets/dir1/`:
```python
out_dir = Path("mock_datasets", "dir1") # directory to put tokenized MIDIs
file_path = Path("mock_datasets", "dir1", "tokens.json") # where the original file lives
data_path = out_dir # mimicking how args pass through data_augmentation_dataset(out_dir, self, *data_augment_offsets)
out_path = data_path # out_path is not given so default behaviour is to copy data_path
saving_path = (
    out_path
    / file_path.relative_to(data_path) # = 'tokens.json'
    / f"{file_path.stem}.json" # = 'tokens.json'
)

saving_path.parent.mkdir(parents=True, exist_ok=True)
```
raises `FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'mock_datasets\\dir1\\tokens.json'`

I propose a solution, we don't want to copy the files of tokens (what I think of as the "original files") generated directly from the MIDI dataset when we pass `data_augmentation_offsets` to `tokenize_midi_dataset` because they are already guaranteed to live in that directory. So I changed `midi_tokenizer.py[1882-1883]` from:
```python
if data_augment_offsets is not None:
    data_augmentation_dataset(out_dir, self, *data_augment_offsets)
```
to disable copying original files:
```python
if data_augment_offsets is not None:
    data_augmentation_dataset(out_dir, self, *data_augment_offsets, copy_original_in_new_location=False)
```

Now the code from the first snippet does what I expected it to do, augment the tokenized dataset whilst keeping original files around:
```
Tokenizing MIDIs (maestro-v3.0.0/tokens_noBPE): 100%|██████████| 5/5 [00:04<00:00,  1.07it/s]
Performing data augmentation: 100%|██████████| 5/5 [00:00<00:00,  7.96it/s]

```

Let me know what you think! I'm not sure if I've just way overcomplicated this issue but I wanted to be as clear as possible.

**Comment by Natooz** [comment]
Hello,

Thank you very much for the bug report and kind comments. 😃
First, there is nothing such as an overlycomplicated issue, the most accurate and complete, the easier it is to fix it! :)
Even better if the solution is provided as you did here!

Indeed, `file_path.relative_to(data_path)` was missing the `.parent` part (as done in the loop just before). And `copy_original_in_new_location` is better to be disabled when calling the method from `tokenize_dataset`.

I included these suggestions + a few improvements in #108 (commits 636039d7d95429cb725bf0f0c0b331a65da67750 and da780db01ec04b75bf443dc4aa9fa6cd1fdd43f3), to make sure that the fixes will be merged soon as I plan a new release next week. Now as you did all the work, if you want it, you can send a PR with the exact same changes made in these commits and I will merge it to "officialise" your contribution.

**Comment by parneyw** [comment]
Hi,
No worries! Glad to have contributed to this project. I'm still learning how to use GitHub so I'm not sure exactly what I would need to do with regards to the PR? I'll give it a go though I'd like to make my contribution official.
Cheers!

**Comment by Natooz** [comment]
Great!
For now you would just to make a fork of the project, then on your fork commit+push the changes, then send the PR here. No need to worry about pre-commit/lint/tests here as the changes are already tested :)
The [official GitHub tutorial](https://docs.github.com/en/get-started/quickstart/contributing-to-projects#) is pretty well made, you can even do everything from your browser

**Comment by parneyw** [comment]
Thanks for the help with PRs. I suppose I'll close this issue now!
