### ISSUE TITLE
What exactly is beat_res?

### ISSUE THREAD

**Issue by parneyw** [Natooz/MidiTok#117]
I've tried looking around in documentation and in docstrings but I can't figure out what the `beat_res` argument for a tokenizer is (and therefore I have always copied the values the examples use).
Would someone be able to explain this and potentially update documentation to make this clearer?
Thanks!

**Comment by Natooz** [comment]
Hi @parneyw ,
Apologies for the late reply, I have been busy lately and totally forgot this issue!

Also apologies, it appears that there is a bug in the docs, the `TokenizerConfig` docs is not showing, I'll handle this shortly. It can be seen in this [previous doc version](https://miditok.readthedocs.io/en/v2.1.6/midi_tokenizer.html#tokenizer-config) for example.

In short, `beat_res` defines the time resolutions (in sample per beat) of a tokenizer. It defines the "granularity" of values such as `Duration` or `Position`/`TimeShift` tokens. And different resolutions can be applied, for example to represent more accurate short values, and reduce the accuracy for longer duration/time intervals values.
Depending on these resolutions, the onset/offset times of the notes and other MIDI events (control changes etc) will be resampled to be aligned.

**Comment by parneyw** [comment]
Thanks for the reply I understand that you're busy! I'm still not totally clear on the idea though so maybe an example would help? For instance, if I wanted to divide each bar into 16th notes how would this be represented by beat_res?

**Comment by Natooz** [comment]
In this case you could use a `beat_res` or `{(0, 4): 4, (4, 8): 2}` for example. Here it means that the tokenizer will have a vocabulary with `Duration` (if applicable) values for 0.25, 0.5, 0.75, 1 bars and 1.5, 2, 2.5... 8 bars.
