### ISSUE TITLE
`tokens_to_midi` returning a MidiFile that has no notes and one instrument

### ISSUE THREAD

**Issue by parneyw** [Natooz/MidiTok#118]
I'm having an issue with converting the output of GPT2 from the transformers module to MIDI which seems to depend on how the model was trained. Models trained with TokDataset have no issues and their output is converted just fine, but when I train a model just using batches of tensors the output tensor is not converted into a valid MIDI somehow.
I'm getting a MidiFile object with one instrument as expected but it always has 0 notes. Any thoughts on why this might be happening? I cannot see how to recreate this issue so all I can do for now is provide the token sequences and tokenizer for inspection for now. If I find a way to recreate the issue I will update this issue.
This is a problem for me because the saved MIDI file cannot be loaded again for playback.
[broken_midis.zip](https://github.com/Natooz/MidiTok/files/13727142/broken_midis.zip)
[valid_midis.zip](https://github.com/Natooz/MidiTok/files/13727145/valid_midis.zip)
[tokenizer.zip](https://github.com/Natooz/MidiTok/files/13727163/tokenizer.zip)

**Comment by Natooz** [comment]
> Models trained with TokDataset have no issues and their output is converted just fine, but when I train a model just using batches of tensors the output tensor is not converted into a valid MIDI somehow.

I'm not sure to understand the difference between the two things done here.
Are you saying that a model trained with DatasetTok outputs valid tensors that you can convert back to MIDIs, but a model trained with another way doesn't?

If the output MIDI has 0 notes, it surely means that the tokenizer didn't detect valid token successions that form notes.

**Comment by parneyw** [comment]
Thanks for the response. You are correct as I finally realised my model wasn't putting out PITCH, VEL, DUR in that order at all, hence no notes being added.
Since this is not the fault of your code I suppose this isn't an issue that needs addressing, but it could be worth adding a warning if no notes were detected in tokens_to_midi conversion?
I apologise for the slight waste of time with this issue!
