### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by kalyani2003** [Natooz/MidiTok#119]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/Natooz/MidiTok/assets/84217977/a93cba42-1db6-4274-890d-522f09c41811)

**Comment by kalyani2003** [comment]
@Natooz  kindly assign me this issue, I want to work on it.  Thank You!

**Comment by Natooz** [comment]
Hi @kalyani2003 , sure that's something that we could add.
Could it be as shown on the image you shared? Would it be dynamically updated/retrieved from the GitHub API?

**Comment by kalyani2003** [comment]
Absolutely Yes @Natooz

**Comment by Natooz** [comment]
Great, looking forward :)
