### ISSUE TITLE
Data Preparation Issues

### ISSUE THREAD

**Issue by laceyp99** [Natooz/MidiTok#126]
I have 2 issues. One is what I believe to be a simple bug, and the other is probably just my understanding of BPE. 

Addressing the potential bug first. When I set one_token_stream=True within my DatasetTok, the dataset seems to be empty. From my understanding, this bool is initialized as False to account for MIDI files with multiple tracks, and my dataset that I'm trying to train with is only single instrument MIDI files. I might be misunderstanding the use of this parameter, but when set to True, the DatasetTok doesn't seem to hold the data properly.

Next is the issue of applying BPE to my dataset. I modified the colab notebook Full Example code in the repo to train GPT2 with my dataset. I used MIDI-Like tokenization, which works and gave me the proper input ids, but when applying BPE to those tokens, I got input ids with only one token for the whole 4 bar MIDI file. I've tried the BPE multiple times, even on the Maestro dataset like in the example, and there are times where it does give me a list of input ids that is longer than one and seems to be correct. Although whenever I try to use those input ids within the dataset, I get an error saying "IndexError: index out of range in self" relating to the embedding layer. I'm still trying to fully understand BPE and other machine learning techniques, so any clarification or advice would be greatly appreciated!

**Comment by Natooz** [comment]
`one_token_stream` being `True` basically means that the tokenizer will tokenize each MIDI track separately, hence returning a list of `TokSequence`s (one for each track).
This attribute is usually disabled when the tokenizer handle *Program* tokens.

For the BPE issue, what are the number of files you trained the tokenizer with and the final vocabulary size?
My guess is that you used a very small amount of training data, hence the tokenizer basically learned whole sequences as one token.

Don't hesitate to insert code and errors tracebacks here, as it would be easier to "debug" and find solutions.

**Comment by laceyp99** [comment]
Your guess is totally correct. I was testing the code with a very small dataset initially and looking to build a bigger personal dataset  later on. I can see how the BPE reacted in that way. I found your page [Byte Pair Encoding for Symbolic Music](https://natooz.github.io/BPE-Symbolic-Music) which is helping me understand the use and effect of the BPE. I'm going to flesh out the dataset and find the correct vocab size. Also thanks for the clarification on the one_token_stream. I'll reach out if I run into any issues further down the line.
