### ISSUE TITLE
Need Help! I run the Full_Example_HuggingFace_GPT2_Transformer.ipynb but the output is none 

### ISSUE THREAD

**Issue by sunyrain** [Natooz/MidiTok#128]
It happened in the last cell

```
midi = tokenizer.tokens_to_midi([deepcopy(generated.tolist())], time_division=384)
        print(midi)
        print(len(midi.instruments[0].notes))
```

When I print(midi),I got things like

```
ticks per beat: 384
max tick: 1392
tempo changes: 18
time sig: 1
key sig: 0
markers: 0
lyrics: False
instruments: 1
```
But when I  print(len(midi.instruments[0].notes))
I got 0

it seems that tokenizer.tokens_to_midi doesn't work?
```
for batch in tqdm(dataloader_test, desc='Testing model / Generating results'):  # (N,T)
    res = model.generate(
        inputs=batch["input_ids"].to(model.device),
        attention_mask=batch["attention_mask"].to(model.device),
        generation_config=generation_config)  # (N,T)

    # Saves the generated music, as MIDI files and tokens (json)
    for prompt, continuation in zip(batch["input_ids"], res):
        generated = continuation[len(prompt):]
        midi = tokenizer.tokens_to_midi([deepcopy(generated.tolist())], time_division=384)
        print(midi)
        print(len(midi.instruments[0].notes))
        tokens = [generated, prompt, continuation]  # list compr. as seqs of dif. lengths
        tokens = [seq.tolist() for seq in tokens]
        for tok_seq in tokens[0:]:
            _midi = tokenizer.tokens_to_midi([deepcopy(tok_seq)], time_division=384)
            midi.instruments.append(_midi.instruments[0])
        midi.instruments[0].name = f'Continuation of original sample ({len(generated)} tokens)'
        midi.instruments[1].name = f'Original sample ({len(prompt)} tokens)'
        midi.instruments[2].name = f'Original sample and continuation'
        midi.dump(gen_results_path / f'{count}.mid')
        tokenizer.save_tokens(tokens, gen_results_path / f'{count}.json')
        count += 1
```
I printed len(generated) and it was right, but after tokenizer.tokens_to_midi, it turned to be 0

**Comment by Natooz** [comment]
Hi,

What is the length of the `generated` sequence?
The problem here is very likely to be the model not generate correct sequences of tokens, that actually form notes (successions of pitch -> velocity -> duration tokens).

**Comment by sunyrain** [comment]
Thanks for your help, I only trained about 3000 steps to get a quick test. most of the generated sequences have only one note
![image](https://github.com/Natooz/MidiTok/assets/89635780/858b7f67-b9d2-4ca1-b49e-e1dcac8a0175)

I just ran the code in the repo, so how can I fix it ?Thanks

**Comment by Natooz** [comment]
Hi 👋
(first apologies for the late reply).
It appears that only one token is generated when calling `model.generate()`.
This means that either the `max_length` is set to a value equal to the length of the sequences in the input batch (`batch["input_ids"]`), or the `max_new_tokens` parameter is set to 1.

You can get all the details and tune the generation config in the [hugging face documentation](https://huggingface.co/docs/transformers/main_classes/text_generation) 🙌

**Comment by sunyrain** [comment]
Thank you very much!
