### ISSUE TITLE
[Enhancement] Versionning documentation

### ISSUE THREAD

**Issue by leleogere** [Natooz/MidiTok#133]
> this docs is a bit too "up-to-date" as it concerns the incoming MidiTok V3 but the concerned paragraph is still 100% relevant

As you mentioned in [this comment](https://github.com/Natooz/BPE-Symbolic-Music/issues/2#issuecomment-1895689315), the current documentation might not match the version of Miditok that people are using. It would be very useful to be able to use the bottom-left button of the website to see the documentation of a particular version. Currently, we can see that all versions are referenced, but only the last one is documented. Clicking on any of the previous versions ends up on a 404 error.

![image](https://github.com/Natooz/MidiTok/assets/71326140/3bfddb12-e008-4614-9f8d-5356149411e7)

![image](https://github.com/Natooz/MidiTok/assets/71326140/ad84b36c-cf0a-41ab-83f5-9ee845a7f331)

**Comment by Natooz** [comment]
I do not get 404 errors when I try older versions.
Are you accessing to a particular page that might not exist on older versions?

https://miditok.readthedocs.io/en/v2.1.8/

**Comment by leleogere** [comment]
Woops, that's my bad, I was on a page that didn't exist previously indeed... Problem solved I guess! :sweat_smile:

**Comment by leleogere** [comment]
The issue was that I was on the "Bases" page (first item on the left menu, as showed in my screenshots), which I expected to be in most versions. I appear that it exists both in 3.0.0 and 2.1.8 (and earlier), but that do not share the same URL. In 3.0.0, the "Bases" is located at `https://miditok.readthedocs.io/en/latest/bases.html`, and in 2.1.8 (and earlier) it is located at `https://miditok.readthedocs.io/en/v2.1.8/midi_tokenizer.html`.

**Comment by Natooz** [comment]
Indeed the doc file has been renamed to match the page title 😄
