### ISSUE TITLE
Docs and code bug

### ISSUE THREAD

**Issue by oiabtt** [Natooz/MidiTok#135]
in docs(https://miditok.readthedocs.io/en/latest/examples.html), you pass list
```
midi_paths = list(Path("path", "to", "dataset").glob("**/*.mid"))
augment_midi_dataset(
    midi_paths,
```
but in code, it's different
https://github.com/Natooz/MidiTok/blob/e6bdebda9d75b4aa5484d46be2000460b1f6672c/miditok/data_augmentation/data_augmentation.py#L17
https://github.com/Natooz/MidiTok/blob/e6bdebda9d75b4aa5484d46be2000460b1f6672c/miditok/data_augmentation/data_augmentation.py#L38

```
data_path: Path | str,
```
and ".midi" is ignored

https://github.com/Natooz/MidiTok/blob/e6bdebda9d75b4aa5484d46be2000460b1f6672c/miditok/data_augmentation/data_augmentation.py#L76

**Comment by Natooz** [comment]
Hi, thank you for the catch!
Indeed this should be fixed! For the file extensions we can use `miditok.constants.MIDI_FILES_EXTENSIONS `
Do you want to make the code contribution or should I do it?
