### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'Ignore'

### ISSUE THREAD

**Issue by dedededefo** [Natooz/MidiTok#15]
![image](https://user-images.githubusercontent.com/103300829/180384656-fd6ecaff-058c-4db3-8a64-e7a81c15f8dd.png)
ValueError: invalid literal for int() with base 10: 'Ignore'

**Comment by Natooz** [comment]
Hi, this error happened when decoding sequences of tokens with invalid values.

It has been resolved in 956738765147d7935088eb9e3e55bc8a4ab37271
I'll release the update today

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180399930-e636e5e6-7817-4c0c-aebe-a28f17903717.png)

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180400157-e4bf2b33-ef6f-4ab5-bb88-72980ae4e2c8.png)
this is my get_tokenizer()

**Comment by dedededefo** [comment]
> ![image](https://user-images.githubusercontent.com/103300829/180400157-e4bf2b33-ef6f-4ab5-bb88-72980ae4e2c8.png) this is my get_tokenizer()

Should I add a time signature parameter

**Comment by Natooz** [comment]
My pleasure!

Yes, for this one you just have to add the `TimeSignature` entry in the `additional_tokens` dictionary, as:
```Python
additional_tokens = {
            'Chord': True,
            'Rest': True, 
            'Tempo': True,
            'TimeSignature': False,
            'rest_range': (2, 8),
            'nb_tempos': 32,
            'tempo_range': (40, 250),
            'Program': False
        }
```

Note that time signatures are not used with compound word. I'll add a line in CPWord to automatically set it to False, and update the readme where TimeSignature is absent from `additional_tokens`, thanks for the report! :)

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180403461-f6daad31-5d4b-44c2-8185-ad04cd32d6df.png)
Hi！Thank you for your patience! At the same time, I encountered a new problem

**Comment by Natooz** [comment]
After creating the tokenizer, what does this returns ?
```Python
for i, vocab in enumerate(tokenizer.vocab):
    print(f'vocab {i}: {len(vocab)} tokens')
```

**Comment by dedededefo** [comment]
> After creating the tokenizer, what does this returns ?
> 
> ```python
> for i, vocab in enumerate(tokenizer.vocab):
>     print(f'vocab {i}: {len(vocab)} tokens')
> ```

![image](https://user-images.githubusercontent.com/103300829/180410299-9d735499-163c-4039-9d6c-e04a983c2e49.png)

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180411941-e50365ff-6882-4a3f-a341-0d739980e29f.png)

**Comment by dedededefo** [comment]
It's OK for me to rewrite MIDI using the existing MIDI data. I compare the type of data sequence generated by the model with the existing MIDI data type and find that it is consistent. Both the list and int meet the input requirements

**Comment by dedededefo** [comment]
> 我可以使用现有的 MIDI 数据重写 MIDI。我将模型生成的数据序列的类型与现有的 MIDI 数据类型进行比较，发现是一致的。list 和 int 都满足输入要求

![image](https://user-images.githubusercontent.com/103300829/180413455-4cca7bf0-7690-4a68-a8a2-93ecc41c547d.png)

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180413584-278a3b30-64ee-4237-a83f-80dd12a4e892.png)
![image](https://user-images.githubusercontent.com/103300829/180413617-9b24f8f3-6dbf-4bbd-9a48-b8c59ddb6bc8.png)
Maybe is the problem of vocab2token()?

**Comment by Natooz** [comment]
Ok, the error is caused because the you are trying to decode a token where the first index (token family) of value 3, whereas the vocabulary only contains 3 tokens (0 to 2).

What is the role of `vocab2token` ? Why is it incrementing tokens ?
As `gen` are sampled tokens, should it just be enough to pass it through `tokenizer.tokens_to_midi` ?

**Comment by dedededefo** [comment]
Because I did token2vocab during model training, I got the corresponding vocab when the model generated midi. I need to restore it to token and then generate midi
![image](https://user-images.githubusercontent.com/103300829/180416192-fc2f17d5-6bd2-43c6-a987-d921075d2350.png)
I'm trying to use Gen directly to generate

**Comment by dedededefo** [comment]
I feel I need to retrain the model！Thank you for your advice! be deeply grateful！

**Comment by Natooz** [comment]
You are welcome, thank you for the bug reports!
I am still not sure about the purpose of `token2vocab` and `vocab2token`, as the tokens given by miditok should be well formatted to be used directly with a model (ranging from 0 to len(vocab)).

**Comment by dedededefo** [comment]
> 好的，错误是因为您试图解码第一个索引（令牌系列）值为 3 的令牌，而词汇表仅包含 3 个令牌（0 到 2）。
> 
> 的作用是`vocab2token`什么？为什么要增加令牌？ 与`gen`采样令牌一样，是否足以通过它`tokenizer.tokens_to_midi`？



> 不客气，感谢您的错误报告！ 我仍然不确定 and 的用途`token2vocab`，`vocab2token`因为 miditok 给出的标记应该被很好地格式化以直接与模型一起使用（范围从 0 到 len(vocab)）。
Hello! Sorry, I went to dinner just now! Because I'm running netpi / compound word transformer tensorflow code now, I don't quite understand why It need to add tokens. It seems that It refer to the paper compound word transformer
![image](https://user-images.githubusercontent.com/103300829/180424806-a9690122-cd20-449e-a4a0-ebaf43120fa8.png)

**Comment by dedededefo** [comment]
![image](https://user-images.githubusercontent.com/103300829/180425868-acecfbdd-2c21-4a50-963b-257fa899fd79.png)
It seems that a [eos]family token is added

**Comment by Natooz** [comment]
I am not quite sure this is what is done. 🤷‍♂️
If you want to use SOS / EOS tokens you would have to specify it when creating the tokenizer:
```Python
tokenizer = CPWord(sos_eos_tokens=True, mask=True). # mask not useful here 
```
The vocabulary(ies for CPWord) will then contain these tokens that can be retrieved with `tokenizer.vocab[token_type_index]['SOS_None']` :)

**Comment by JinayJain** [comment]
I'm also seeing this error while using the MIDILike tokenization
![image](https://github.com/user-attachments/assets/190e20e4-3923-4704-96e2-ee39d333e1f0)

I did some poking around and saw this was when the model outputs a NoteOn token but doesn't follow it with a Velocity token.

**Comment by Natooz** [comment]
You can solve this issue by installing MidiTok from git: `git install git+https://github.com/Natooz/MidiTok`. It has been fixed recently but the next package version hasn't been released yet.

**Comment by JinayJain** [comment]
Awesome, thanks @Natooz
