### ISSUE TITLE
Error running the 2nd example in readme

### ISSUE THREAD

**Issue by MikeMpapa** [Natooz/MidiTok#157]
When I do: `tokenizer.learn_bpe(vocab_size=30000, files_paths=midi_paths)`
 I get : ` self._bpe_model.train_from_iterator(
TypeError: 'PosixPath' object cannot be converted to 'PyString'`

I converted the paths to string but then it seems to learn the filenames instead of the file content:
<img width="1165" alt="Screenshot 2024-03-28 at 4 05 24 PM" src="https://github.com/Natooz/MidiTok/assets/12614646/5bd16125-8f6f-412c-8322-7545a881ab7f">

**Comment by Natooz** [comment]
What versions of miditok and tokenizers (hugging face lib) are you using?
I just ran it without errors with the latest miditok version and tokenizers==0.15.0

**Comment by MikeMpapa** [comment]
I am on miditok==3.0.2 & on 0.15.2 (tried also with 0.15.2) but I am seeing the same error

**Comment by Natooz** [comment]
Can you paste here the exact code you are running?
Are you sure you are not running `tokenizer.learn_bpe(vocab_size=30000, midi_paths)` instead of `tokenizer.learn_bpe(vocab_size=30000, files_paths=midi_paths)`?

**Comment by MikeMpapa** [comment]
it seems that the initial error was an IDE problem - apologies for that. 
However now, I do get a tokenizer.json but with the following warnings:

```
nanobind: leaked 3 instances!
 - leaked instance 0x103c2e9a8 of type "Tick"
 - leaked instance 0x118ab20a8 of type "Second"
 - leaked instance 0x103c2ea08 of type "Quarter"
nanobind: leaked 61 types!
 - leaked type "symusic.core.TextMetaQuarter"
 - leaked type "symusic.core.TempoQuarterList"
 - leaked type "symusic.core.Iterator"
 - leaked type "symusic.core.PitchBendSecondList"
 - leaked type "symusic.core.NoteQuarter"
 - leaked type "symusic.core.PedalTick"
 - leaked type "symusic.core.TimeSignatureSecond"
 - leaked type "symusic.core.PitchBendTickList"
 - leaked type "symusic.core.ControlChangeSecond"
 - leaked type "symusic.core.PitchBendSecond"
 - leaked type "symusic.core.ScoreTick"
 - ... skipped remainder
nanobind: leaked 1436 functions!
 - leaked function "count"
 - leaked function "__repr__"
 - leaked function ""
 - leaked function ""
 - leaked function ""
 - leaked function "__ne__"
 - leaked function "__getitem__"
 - leaked function "__repr__"
 - leaked function ""
 - leaked function "__init__"
 - leaked function "__getitem__"
 - ... skipped remainder
nanobind: this is likely caused by a reference counting issue in the binding code.

```

And then when it enters the split MIDIs section it throws the following error, which makes me assume that the tokenizer has not been trained properly?:

`
 packages/miditok/pytorch_data/split_midi_utils.py", line 294, in get_average_num_tokens_per_note
    num_tokens_per_note.append(len(tok_seq) / num_notes)
                               ~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: division by zero
`

Here is the code:

```
from miditok import REMI, TokenizerConfig
from miditok.pytorch_data import DatasetMIDI, DataCollator, split_midis_for_training
from torch.utils.data import DataLoader
from pathlib import Path

# Creating a multitrack tokenizer, read the doc to explore all the parameters
config = TokenizerConfig(num_velocities=16, use_chords=True, use_programs=True)
tokenizer = REMI(config)

# Train the tokenizer with Byte Pair Encoding (BPE)
midi_paths = list(Path("test_midi_files").glob("**/*.mid"))[:100]
tokenizer.learn_bpe(vocab_size=30000, files_paths=midi_paths)
tokenizer.save_params(Path("tokenizer.json"))
#tokenizer._load_params(Path("tokenizer.json"))

# Split MIDIs into smaller chunks for training
dataset_chunks_dir = Path("midi_chunks")
split_midis_for_training(
    files_paths=midi_paths,
    tokenizer=tokenizer,
    save_dir=dataset_chunks_dir,
    max_seq_len=1024,
)

# Create a Dataset, a DataLoader and a collator to train a model
dataset = DatasetMIDI(
    files_paths=list(dataset_chunks_dir.glob("**/*.mid")),
    tokenizer=tokenizer,
    max_seq_len=1024,
    bos_token_id=tokenizer["BOS_None"],
    eos_token_id=tokenizer["EOS_None"],
)
collator = DataCollator(tokenizer["PAD_None"])
dataloader = DataLoader(dataset, batch_size=64, collate_fn=collator)

# Iterate over the dataloader to train a model
for batch in dataloader:
    print("Train your model on this batch...")
```

**Comment by MikeMpapa** [comment]
It seems that there is something off with my overall setup - the code seems to function as expected on colab

**Comment by jinhonglu** [comment]
> it seems that the initial error was an IDE problem - apologies for that. However now, I do get a tokenizer.json but with the following warnings:
> 
> ```
> nanobind: leaked 3 instances!
>  - leaked instance 0x103c2e9a8 of type "Tick"
>  - leaked instance 0x118ab20a8 of type "Second"
>  - leaked instance 0x103c2ea08 of type "Quarter"
> nanobind: leaked 61 types!
>  - leaked type "symusic.core.TextMetaQuarter"
>  - leaked type "symusic.core.TempoQuarterList"
>  - leaked type "symusic.core.Iterator"
>  - leaked type "symusic.core.PitchBendSecondList"
>  - leaked type "symusic.core.NoteQuarter"
>  - leaked type "symusic.core.PedalTick"
>  - leaked type "symusic.core.TimeSignatureSecond"
>  - leaked type "symusic.core.PitchBendTickList"
>  - leaked type "symusic.core.ControlChangeSecond"
>  - leaked type "symusic.core.PitchBendSecond"
>  - leaked type "symusic.core.ScoreTick"
>  - ... skipped remainder
> nanobind: leaked 1436 functions!
>  - leaked function "count"
>  - leaked function "__repr__"
>  - leaked function ""
>  - leaked function ""
>  - leaked function ""
>  - leaked function "__ne__"
>  - leaked function "__getitem__"
>  - leaked function "__repr__"
>  - leaked function ""
>  - leaked function "__init__"
>  - leaked function "__getitem__"
>  - ... skipped remainder
> nanobind: this is likely caused by a reference counting issue in the binding code.
> ```
> 
> And then when it enters the split MIDIs section it throws the following error, which makes me assume that the tokenizer has not been trained properly?:
> 
> `packages/miditok/pytorch_data/split_midi_utils.py", line 294, in get_average_num_tokens_per_note num_tokens_per_note.append(len(tok_seq) / num_notes) ~~~~~~~~~~~~~^~~~~~~~~~~ ZeroDivisionError: division by zero`
> 
> Here is the code:
> 
> ```
> from miditok import REMI, TokenizerConfig
> from miditok.pytorch_data import DatasetMIDI, DataCollator, split_midis_for_training
> from torch.utils.data import DataLoader
> from pathlib import Path
> 
> # Creating a multitrack tokenizer, read the doc to explore all the parameters
> config = TokenizerConfig(num_velocities=16, use_chords=True, use_programs=True)
> tokenizer = REMI(config)
> 
> # Train the tokenizer with Byte Pair Encoding (BPE)
> midi_paths = list(Path("test_midi_files").glob("**/*.mid"))[:100]
> tokenizer.learn_bpe(vocab_size=30000, files_paths=midi_paths)
> tokenizer.save_params(Path("tokenizer.json"))
> #tokenizer._load_params(Path("tokenizer.json"))
> 
> # Split MIDIs into smaller chunks for training
> dataset_chunks_dir = Path("midi_chunks")
> split_midis_for_training(
>     files_paths=midi_paths,
>     tokenizer=tokenizer,
>     save_dir=dataset_chunks_dir,
>     max_seq_len=1024,
> )
> 
> # Create a Dataset, a DataLoader and a collator to train a model
> dataset = DatasetMIDI(
>     files_paths=list(dataset_chunks_dir.glob("**/*.mid")),
>     tokenizer=tokenizer,
>     max_seq_len=1024,
>     bos_token_id=tokenizer["BOS_None"],
>     eos_token_id=tokenizer["EOS_None"],
> )
> collator = DataCollator(tokenizer["PAD_None"])
> dataloader = DataLoader(dataset, batch_size=64, collate_fn=collator)
> 
> # Iterate over the dataloader to train a model
> for batch in dataloader:
>     print("Train your model on this batch...")
> ```

@MikeMpapa Hi, how did you resolve this leak problem? thank you.

**Comment by MikeMpapa** [comment]
Never fully resolved it unfortunately. Ended up using an alternative way of tokenizing the midis.  if you find something more please share

**Comment by jinhonglu** [comment]
> Never fully resolved it unfortunately. Ended up using an alternative way of tokenizing the midis. if you find something more please share

@MikeMpapa what alternative way are you using?

**Comment by MikeMpapa** [comment]
I used this as my starting point and modified it accordingly to my needs: https://github.com/AI-Guru/MMM-JSB

**Comment by jinhonglu** [comment]
> I used this as my starting point and modified it accordingly to my needs: https://github.com/AI-Guru/MMM-JSB

@MikeMpapa have you tried this https://github.com/MusicLang/musiclang_predict

This seems to be an up-to-date model.

**Comment by MikeMpapa** [comment]
@Natooz yes thanks for clarifying! To be clear the reason I ended up going with an alternative was not MidiTok's insufficiencies but rather a personal choice at that time as it was easier to customize exactly to my needs. I think right now MidiTok would/will be mi go-to. 

@jinhonglu I am aware of MusicLang but (a) license is not as permissive and (b) is much more of a black box framework and customization of the tokenizer is not possible.
