### ISSUE TITLE
cannot import DatasetTok - Error with version 3.0.2

### ISSUE THREAD

**Issue by seb-son** [Natooz/MidiTok#158]
When installing the latest pkg version (3.0.2) with pip inside a conda env on linux (Ubuntu 22.04.4 LTS) and trying to create a dataset and collator with the example code from the docs:

 <html>
      <head>
   
        from miditok import REMI
        from miditok.pytorch_data import DatasetTok, DataCollator
        
        midi_paths = list(Path("path", "to", "dataset").glob("**/*.mid"))
        dataset = DatasetTok(
            files_paths=midi_paths,
            min_seq_len=100,
            max_seq_len=1024,
            tokenizer=tokenizer,
        )
        collator = DataCollator(
            tokenizer["PAD_None"], tokenizer["BOS_None"], tokenizer["EOS_None"]
        )
        from torch.utils.data import DataLoader
        data_loader = DataLoader(dataset=dataset, collate_fn=collator)
        
        # Using the data loader in the training loop
        for batch in data_loader:
            print("Train your model on this batch...")

   </head>
    </html>

I get the error 
ImportError: cannot import name 'DatasetTok' from 'miditok.pytorch_data'

Fix: when downgrading to 3.0.1 manually it works.

Best,
Seb

**Comment by Natooz** [comment]
Hi Seb,

Indeed that `DatasetTok` class has been refactored in the v3.0.2 to make place for a better solution, and the class renamed [`DatasetMIDI`](https://miditok.readthedocs.io/en/v3.0.2/pytorch_data.html#miditok.pytorch_data.DatasetMIDI). The new class takes advantages of the super fast MIDI loading speed of symusic to tokenize the files on the fly when iterating over it, thus getting rid of the previously required pre-tokenization step and memory footprint. 
You can read more in the docs: https://miditok.readthedocs.io/en/v3.0.2/pytorch_data.html
Switching to `DatasetMIDI` should be easy as the initialisation is almost identical, don't hesitate to tell me if you need help!

Now I maybe should have use a warning to make the transition smoother, apologies for this.

**Comment by seb-son** [comment]
I see, sounds good! I would suggest removing the example from the docs as well then :)

**Comment by Natooz** [comment]
Nice catch!
I'm ashamed to have forgotten to update it!
It's now done in #156, thank you!
