### ISSUE TITLE
how can I get tokens like midi_like ?

### ISSUE THREAD

**Issue by li-car-fei** [Natooz/MidiTok#16]
I just want to get tokens of note_on, note_off, velocity, time_shift like the representation in the paper: MUSIC TRANSFORMER: GENERATING MUSIC WITH LONG-TERM STRUCTURE 

how can I get that ?

**Comment by Natooz** [comment]
Hi,

You would need to call the `MIDILike` class, as in:

```python
from miditok import MIDILike
from miditoolkit import MidiFile

# Creates the tokenizer and loads a MIDI
tokenizer = MIDILike()  # uses default parameters
midi = MidiFile('path/to/your_midi.mid')
tokens = tokenizer(midi)
```
