### ISSUE TITLE
Structured tokenizer order is different from documentation

### ISSUE THREAD

**Issue by mister-magpie** [Natooz/MidiTok#169]
I am using the Structured tokenizer for a project and I noticed that encoded files follow the order:
`Timeshift, Pitch, Velocity, Duration`

In the docs however it indicates that the timeshift token should be at the end.  
Is this on purpose or is it bug? In the first case I think the documentation should be updated accordingly.

**Comment by Natooz** [comment]
Thank you for the note.
For structured, the type of the first token (TimeShift of Pitch) isn't really important. If it starts with a Pitch, this means that a the original music file contains a note at the very beginning (tick 0), whereas if it begins with a TimeShift, this means that the first note is actually played after certain period of time (hence time shift).
I hope this cleared things up! 🙌
