### ISSUE TITLE
Trouble understanding Beat Resolution from the README

### ISSUE THREAD

**Issue by rossgreer** [Natooz/MidiTok#17]
Could someone please help provide some clarity on the README for the beat resolution parameter?

It says, "Beat resolution: is the number of samples within a beat. MidiTok handles this with a flexible way: a dictionary of the form {(0, 4): 8, (3, 8): 4, ...}. The keys are tuples indicating a range of beats, ex 0 to 4 for the first bar. The values are the resolutions, in samples per beat, of the given range, here 8 for the first. This way you can create a tokenizer with durations / time shifts of different lengths and resolutions."

I'm having trouble understanding what is meant by "ex 0 to 4 for the first bar". What is meant by (0,4) in the tuple? Since dictionaries are unordered, how do we know that this represents the first bar? If I'm interpreting correctly, this would say "Beats 0 through 4 each contain 8 samples", meaning that the smallest represented unit is the 32nd note for the measure. But, what is meant by (3,8)? Aren't beats 3 and 4 already accounted for in the first tuple? 

Thank you for your help!

**Comment by Natooz** [comment]
Hi,

#If I'm interpreting correctly, this would say "Beats 0 through 4 each contain 8 samples", meaning that the smallest represented unit is the 32nd note for the measure
That’s right.

#But, what is meant by (3,8)?
This applies for the durations. If a note have a duration longer than 4 beats, its value will be quantized by the associated value in the dic (here 4 samples/beat).
It also applies to TimeShift tokens in the concerned representations.


And the onset times of all notes will be quantized to the highest value in the dic (here 8 samples/beat).

Hoping this helps, sorry if this wasn’t clear in the readme / docstring.
