### ISSUE TITLE
Defining Custom Tokens

### ISSUE THREAD

**Issue by MikeMpapa** [Natooz/MidiTok#171]
Hi and thanks for the awesome work! If I want to modify a tokenization scheme and add custom tokens to the vocabulary related to MIDI metadata. How could I do that?

**Comment by Natooz** [comment]
Hi, thank you for these nice words.
The `[tokenizer.add_to_vocab](https://miditok.readthedocs.io/en/v3.0.3/bases.html#miditok.MusicTokenizer.add_to_vocab)` method should be what you are looking for. It allows to add custom tokens to the vocabulary. The tokenizer implemented in MidiTok will however not use them, this is up to you to add them at the appropriate indexes in the token sequences produced.
Alternatively, you can also subclass one of the tokenizer class and [override the required methods](https://miditok.readthedocs.io/en/v3.0.3/tokenizations.html#create-yours) to potentially inject your custom tokens more easily at the right places.
