### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by shawn120** [Natooz/MidiTok#178]
```
Building wheel for symusic (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for symusic (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [203 lines of output]
```
...
```
ERROR: Failed building wheel for symusic
Failed to build symusic
ERROR: Could not build wheels for symusic, which is required to install pyproject.toml-based projects
```
Same error if i try to install symusic first

**Comment by shawn120** [comment]
Find solution here #155

**Comment by shawn120** [comment]
> What is your [cpu arch](https://itsfoss.com/arm-aarch64-x86_64/) and OS? Are you explicitly installing symusic from source?

I tried both from pip and from source. and got the same error
My cpu arch: x86_64
os: CentOS Linux release 7.9.2009 (Core)

**Comment by shawn120** [comment]
I looked thru #155 and tried install from source but still fail for the same error

**Comment by shawn120** [comment]
Tried this way too. Still got the same error
https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797

**Comment by Natooz** [comment]
Pinging @Yikai-Liao as he will probably be of better help than me.

Are there more details on the logs as to why the compilation is failing?

**Comment by shawn120** [comment]
> Pinging @Yikai-Liao as he will probably be of better help than me.
> 
> Are there more details on the logs as to why the compilation is failing?

Sorry there was a typo in my command earlier, I solved it by using this way https://github.com/Natooz/MidiTok/issues/155#issuecomment-2027122797

Thank you for helping me!
