### ISSUE TITLE
How to choose the vocab_size for training a bpe tokenizer?

### ISSUE THREAD

**Issue by paranoid2droid** [Natooz/MidiTok#179]
Thanks for your contribution to this fantastic work!

I noticed that a default vocab_size of 30,000 is used in the examples, but I wonder if there are any thumb of rules for setting this value?

What are the important factors for choosing the vocab size, such as number of MIDI files, length of MIDI files, or something else?

**Comment by Natooz** [comment]
Hi,

I actually do not have definitive answers as there is not much research on this question.
It would say that the "optimal" vocabulary size depends on your model size (the larger the embedding space is, the most tokens is should easily contain without too much "collisions") and the size of your dataset (in absolute number of base tokens).
You're probably safe with values between 20k and 30k as it already considerably reduces the sequence lengths without overfitting. If you want to try larger size, what you can do is probably measure the tokenizer overfitting and stop when it begins to learns tokens that are only present a few times in the dataset (and/or in too few data samples).

**Comment by paranoid2droid** [comment]
Thanks for your quick response! 

It seems that we can only verify by experiments but it is inspiring! Thanks!

Another question:
If the MIDI files in the dataset are short snippets, such as only containing less than 10 notes, the corresponding tokenized sequences can be short too (dozens of tokens). In such cases, will bpe tokenizers also benefit the model training?

**Comment by Natooz** [comment]
Sorry for the late answer.
In such case sequences can still being further reduced and It's always better for a model to be trained with tokens with larger amounts of information per token.
Actually even with large files, the average "length" in number of notes per learned tokens remain quite low (in the order of 4~10 for up to 20k/30k vocab depending on the size and diversity of the data)

**Comment by paranoid2droid** [comment]
Sorry for the late response.
Thank you very much for the inspring discussions! I tried with 20k tokens with a large dataset and it works well.
I will close this issue.
Thanks again for your amazing work!
