### ISSUE TITLE
Environment Issue (Nanobind Error)

### ISSUE THREAD

**Issue by MHZ9825** [Natooz/MidiTok#190]
Hey! Thanks for your brilliant work. However, when I'm trying to train a tokenizer on my own dataset, there is a nanobind error, and after checking all the issues, I still have no idea on how to fix it, if you have any advice? 
`Invoked with types: symusic.core.NoteTickList
nanobind: leaked 3 instances!
nanobind: leaked 58 types!
 - leaked type "symusic.core.PedalTickList"
 - leaked type "symusic.core.PitchBendSecond"
 - leaked type "symusic.core.TempoSecond"
 - leaked type "symusic.core.Iterator"
 - leaked type "symusic.core.Quarter"
 - leaked type "symusic.core.TextMetaQuarter"
 - leaked type "symusic.core.PitchBendTickList"
 - leaked type "symusic.core.KeySignatureTick"
 - leaked type "symusic.core.TextMetaTick"
 - leaked type "symusic.core.ControlChangeTick"
 - leaked type "symusic.core.ControlChangeTickList"
 - ... skipped remainder
nanobind: leaked 1259 functions!
 - leaked function "__setstate__"
 - leaked function "__eq__"
 - leaked function "shift_pitch"
 - leaked function "__getitem__"
 - leaked function "__delitem__"
 - leaked function ""
 - leaked function "__repr__"
 - leaked function "__delitem__"
 - leaked function "__iter__"
 - leaked function "shift_time"
 - leaked function "remove"
 - ... skipped remainder
nanobind: this is likely caused by a reference counting issue in the binding code.`

**Comment by Natooz** [comment]
Hey, thank you for your message.
It's not an error per say, but a warning coming from symusic.
I don't know its exact cause but I had it too on macOS and Python 3.9
https://github.com/Yikai-Liao/symusic/issues/43

**Comment by MHZ9825** [comment]
Indeed, I've checked the issues of symusic, it seems that nanobind v2.0.0 leads to this problem [https://github.com/Yikai-Liao/symusic/issues/40](url)

**Comment by Yikai-Liao** [comment]
Here are the related issues:
* https://github.com/Yikai-Liao/symusic/issues/49
* https://github.com/wjakob/nanobind/issues/644

To summarize, `tokenizers` can cause some **global variables to leak** in some cases. For such memory leaks, `pybind11` does not warn, while `nanobind` does by default. However, we can **disable** this warning with a few settings, even though it may seem like a cover-up.

And currently, I'm not sure it is a bug of python or tokenizers.

There are 3 things we could do I think:
1. Suppress the warnings, and allow warnings to be turned on with the option in pip install
2. Using a `yield` based iterator.
3. Open an issue in tokenizers (I'll do this) and try to find the root

**Comment by Natooz** [comment]
Thank you for looking into this!
I have been experiencing these warning since the switch to nanobind too. Until now, I mostly just ignored them as I didn't had the time to focus on actually dealing with them. I am actually not sure that the problem only happens when using the tokenizers library. From now on, I'll try notice more specifically when they happen and report if I can bring additional insights.
