### ISSUE TITLE
split_files_for_training() throws error: pyvec::index out of range: -1

### ISSUE THREAD

**Issue by kroll-software** [Natooz/MidiTok#195]
with some files it runs successfully, for a bigger dataset I get this error.

Thanks in advance

**Comment by kroll-software** [comment]
I had miditok 3.0.3 installed from pip.
miditok 3.0.4 installed from sources solves the problem.

**Comment by Natooz** [comment]
Ok great!
Note sure what was fixed but I'll keep this on my mind if the issue ever occurs again.
