### ISSUE TITLE
Using pitch bend in Octuple tokenizer

### ISSUE THREAD

**Issue by Neptune-S-777** [Natooz/MidiTok#196]
Hi, thank you for your amazing work! I was wondering if there is a way to add the pitch bend attribute to the octuple tokenizer. Is it necessary to create a new tokenizer for this, or is there an existing variable for it?

**Comment by Natooz** [comment]
Hi, unfortunately I don’t think that pitch bends can be integrated in Octuple. Octuple works by having one token per note. While we can embed tempo and time signatures into the mix as they are « global » features, pitch bends aren’t and would break the « continuity ». Maybe they could be integrated into MuMIDI.
I actually recommend to use oser tokenizers (REMI, TSD, MIDILike) to get all the additional tokens that you want + training the tokenizer with BPE/Unigram to get the best results

**Comment by Neptune-S-777** [comment]
Cool, thanks for your recommendation! I think the best option for me is to encode with REMI and organize the attributes in the octuple token format.
