### ISSUE TITLE
Add triplets encoding/representation

### ISSUE THREAD

**Issue by asigalov61** [Natooz/MidiTok#211]
Hey Nathan and MidiTok devs,

It's been a while since I have contributed so I wanted to stop by and say hi! :)

First of all, congrats on MidiTok success and progress/development! I have been following all updates with great interest, and it was nice to see all of them. I remember what it was back when you just started developing it so it's nice to see great improvements :)

The main reason I am writing, however, because I was wondering if you would consider adding my triplets encoding to MidiTok? It showed very good results, and it is very efficient all at the same time.

Here is what I would love to see:

```[delta-start-times, pitches+patches, durations+velocities]```

This allows for 2730 notes per 8192 seq_len @ ~18k dict size.

You can check out how it was implemented and how it performs on my Hugging Face Space (which was space of the week recently btw)
https://huggingface.co/spaces/asigalov61/Giant-Music-Transformer

Such encoding, assuming sane encoding ranges, produces very good results all things considered and compared to other encodings/representations schemes.

I can't submit a PR on my own because MidiTok code is too complex for me to modify proerly. However, I would be willing to advise you every step of the way if you will choose to implement it.

And last but not least, I wanted to ask Nathan to email me to alexlev61@proton.me because I have a few questions about papers on notes/durations and BPE.

Please let me know.

Sincerely,

Alex

**Comment by Mintas** [comment]
@asigalov61  Hi, Alex!
Do you have some kind of paper describing what this type of encoding is in details?
I've been following some of your work (and it is really great and intriguing) for quite some time now and wonder why you haven't published your results as a paper or at least a preprint on arxiv.org.
It's really hard to compare your results with what already exists in the literature and open source.

So not speaking as a developer of Miditok, but as a customer of this library, I'd like to be able to make the most informed choice of the available tools as possible =)

**Comment by Natooz** [comment]
Hi Alex, thank you for your message! :)

I think this is something that we could implement in MidiTok! But we should first clarify/specify how this should be done: 1) how should the tokens and their successions be defined while integrating well with MidiTok; 2) how should we detect the triplets? Because real data is messy and I assume that some sort of time tolerance should be implemented to efficiently detect them. Velocities between successive notes might defer too, should we use the average of the three?

For the token succession I think using something like Triplet-Pitch1-Pitch2-Pitch3-Velocity. That would interface well with everything else, without increasing the vocabulary size and benefit from BPE.

**Comment by asigalov61** [comment]
@Mintas Hi Dmitrii,

Thank you for following my work and research. It means a lot to me :)

Unfortunately, I am way behind on publishing results of my research because it only just matured and because I am a solo researcher. I simply did not have time yet to describe my research and results. Up until now I have been putting emphasis on publishing practical code/implementations/models so that those interested could try it and/or put it to good use.

I do plan to write up best of my research within next year or so. I can let you know once I am able to do it because I agree that it would help you and others to understand my work better.

For now, please kindly refer to my demos/spaces on Hugging Face. Since this is music, its most important to HEAR the results so to speak and IMHO. In fact, I often found that good-looking results published in papers did not produce good real-life music results.

Hope this makes sense.

If you have any specific or current questions, I would be more than happy to answer them on GitHub or in private. Feel free to open an issue/discussion in a repo you are interested in or email me privately at my public email.

**Comment by asigalov61** [comment]
@Natooz Thank you for your response, Nathan.

Could you please kindly clarify your questions... 

What do you mean by detecting triplets and averaging velocities?

To elaborate, I was proposing adding a triplet encoding as another main standard template to MidiTok, like you did with REMI for example. Alternatively, it can be integrated as one of the custom templates.

In regard to encoding itself:

I am proposing symmetrical triplets encoding so that the sequence of notes/tokens is always divisible by three.
The detailed format is such: [delta-start-time, (patch * 129) + pitch, (duration * 8) + velocity]

In regard to BPE compatibility...I am not sure here because of the dict size but it is still possible I think if you will tell me what you are most concerned about.

Hope this makes sense.

Sincerely,

Alex

**Comment by Natooz** [comment]
About detecting triplets: I assume that in many cases, in particular performance/recorded data, triplets won't have perfect notes onsets/offsets. We must design a method that can efficiently distinguish "real" triplets from false positives. That can be inspired from the current chord detection method which relied on node onsets with a slight time offset tolerance.

> To elaborate, I was proposing adding a triplet encoding as another main standard template to MidiTok, like you did with REMI for example. Alternatively, it can be integrated as one of the custom templates.

Sorry for the misunderstanding, I thought you meant to add an additional token type that could integrate oob with already existing tokenizations.
I'm not sure to fully understand the signification of the token succession you provided. Can you elaborate? What do you refer to as "patch"?

> In regard to BPE compatibility...I am not sure here because of the dict size but it is still possible I think if you will tell me what you are most concerned about.

Generally, I think it is better to have a small "base" vocabulary (think of it as the alphabet and syntax characters), and then build a much larger one based on the frequency of the successions of these "base" tokens/characters. This automatically create the tokens that will be used the most, i.e. reduce sequence length while making the model learn more "information-dense" embeddings. Plus the user keeps the flexibility of choosing its own vocabulary size.

**Comment by asigalov61** [comment]
@Natooz Thank you for the clarifications.... I think I can better explain my idea to you now... :)

In my triplets, start-time is represented by a single token, so existing MidiTok methods of detection of onsets can be used. There is nothing special or different about it.

If I understood you correctly, you would prefer working with token types, rather than particular encoding schemes. It's totally fine with me and we can do it either way. I do not mind.

If you would rather work with token types, we can simply add a "stacked token" type to MidiTok. I do not believe you have such type. By "stacked token" I mean a token which would represent two or more tokens by a single token. Think of it as BPE for tokens types.

By stacking I mean polynomial representation/positional notation. So if our start times are represented by 0-32, durations by 0-32, and pitches by 0-127, and the example note is 10, 10, 60, the stacked token would be 128*32*10 + 32*10 + 60 = 41340

This is what how they encoded pitches+velocities+instruments/patches in MuseNet - a triple-stacked token.

=====

In regard to patches - this is how I call MIDI patches or instruments.

In regard to BPE, from my experience BPE does not produce good results with music. Yes, its efficient and the model loss/acc can look good but the models ability to do a continuation for example would be diminished with BPE from my experience. I am most concerned with continuations so your experience in other tasks could've been different which is totally fine.

BPE can be used on stacked tokens but it would need a large dataset.

**Comment by asigalov61** [comment]
@Natooz I figured that I would elaborate mathematically so that its more understandable:

```
pitch_token = 60 # 0 - 127
instrument_token = 0 # 0 - 9
velocity_token = 15 # 0 - 15

stacked_token = pitch_token * 16 * 10 + instrument_token * 16 + velocity_token # tirple-stacked token

>>> 9615
```

```
pitch_token = stacked_token // 16 // 10
instrument_token = stacked_token // 16 % 10
velocity_token = stacked_token % 16

pitch_token, instrument_token, velocity_token

>>> (60, 0, 15)
```

So it can really be just a method in MidiTok TokenizerConfig or a separate method for MidiTok tokenizer.

Does it make sense?

Alex

**Comment by Natooz** [comment]
Thank you for the examples, I understand better the design.

I would maybe add that this is actually what BPE does, but by learning the tokens from the data instead of creating a vocabulary of values combinations. In this regard, I doubt that it will perform better.
Using combined tokens (« stack » makes me think more of CPWord or Octuple) could be a configuration parameter, but this would require us to offer a flexible way to users to combines the types that they want more or less freely (when applicable, e.g pitch/velocity/duration)

**Comment by asigalov61** [comment]
@Natooz Thank you.

Yes, if you could add such functionality (stacked tokens) it would be great! It would allow me to use MidiTok with my existing models and for my future projects.

Yes, it would require a method to allow users to select which tokens to stack. But due to polynomial nature of such stacking, you can limit it. I.e up to 3 or 4 tokens max.

Actually, combining tokens improves the performance significantly because it makes encoding more logical and natural in terms of elements. They did it with MuseNet and it worked great.

So, please think about it and if possible, please add it. I would really appreciate it :)

I am closing this issue unless you need me to elaborate more.

Sincerely,

Alex

PS. Please email me, at your convenience to alexlev61@proton.me. I have a few questions for you about BPE and your other paper. Thank you.

**Comment by asigalov61** [comment]
@Natooz Thank you, Nathan. It's totally fine. And I really appreciate your time and responses :)
