### ISSUE TITLE
Is possible to initialize a tokenizer from a previously learned BPE?

### ISSUE THREAD

**Issue by balditommaso** [Natooz/MidiTok#23]

**Comment by Natooz** [comment]
Hi, 👋
Yes this is possible. (sorry that there is not much documentation)

When learning BPE, you should provide an `out_dir` argument that will actually save the tokenizers parameters to a config.txt file.

And later, you can create a tokenizer with the `params` argument as the path to the config.txt file, that will load all the previously learned vocabulary, e.g. `tokenizer = REMI(Path("to", "config.txt"))`
