### ISSUE TITLE
Hugging face note book not working, not running in Colab

### ISSUE THREAD

**Issue by braindamp** [Natooz/MidiTok#31]
one the 2nd cell of the notebook, I get "class DataCollatorGen(DataCollatorMixin):"

then commenting it out, gives me:

KeyError: 'SOS_None'

**Comment by Natooz** [comment]
Hey 👋
Just fixed it, tell me if you find other bugs

**Comment by braindamp** [comment]
@Natooz thanks, but still having the same issue.. 

name 'DataCollatorMixin' is not defined

`# Creates the tokenizer convert MIDIs to tokens
tokens_path = Path('m_tokens')
tokens_paths = list(Path(tokens_path).glob("**/*.json"))
tokenizer = REMI(pitch_range, beat_res, nb_velocities, additional_tokens, special_tokens=special_tokens) # REMI
midi_paths = list(Path('/content/drive/MyDrive/midiset').glob('**/*.mid'))
tokenizer.tokenize_midi_dataset(midi_paths, tokens_path)
`

I changed the tokens_paths to add Path, as it says wasn't posix iterable

**Comment by braindamp** [comment]
DataCollatorGen(DataCollatorMixin) 

both of those terms aren't in the new transformers library. What version of transformers are you using? I tried "transformers==4.12.5" as that's where the DataCollatorGen is mentioned. On the hugging face site there's absolutely no mention of them 4.27

**Comment by braindamp** [comment]
got a bit hacky here, and tried to sort it out: https://colab.research.google.com/drive/1D6-wkhJgRXVfb40JP3yHGEOUuWyjabWM?usp=sharing

Had to take out the whole "DataCollatorGen(DataCollatorMixin)" which honestly looks like it was doing something important to do with padding.

**Comment by ufsteven** [comment]
Try adding this statement:
`from transformers.data.data_collator import DataCollatorMixin`

I'm using transformers==4.26.1 and this statement is available.

**Comment by Natooz** [comment]
@ufsteven thank you for the hint !
I finally ran the notebook entirely and corrected all bugs. It should good now.
I also changed the dataset, using now Maestro, as the JSB url was unaccessible, I hope they did not remove it.
