### ISSUE TITLE
MMM track tokenizer

### ISSUE THREAD

**Issue by juancopi81** [Natooz/MidiTok#40]
Hi,

Great library! I am just getting familiar with it. I was wondering if there is any intention to implement the [MMM tokenizer](https://jeffreyjohnens.github.io/MMM/). I would like to train a GPT-2 model on a subset of the LMD clean dataset, and I am familiar with this tokenizer. 

If the MMM tokenizer implementation is not on the roadmap, I would greatly appreciate any guidance or suggestions on alternative tokenizers that could be used with the existing MIDI tokenizers on the library. I'm specifically interested in tokenization methods suitable for GPT-2 models for the LMD clean dataset (multi-track midi files).

Thanks!

**Comment by Natooz** [comment]
Hi, 👋

Thanks for your message !
There is no plan to implement it right now, but it shouldn't too difficult / take much time, I can probably do it in the week.

In the meantime, you can use REMI+ which also support multiple instruments, and is more suited for "continuous" generation (whereas MMM is more for inpainting). I recommend to disable time signature, the bar embedding and additional tokens in the first time to reduce the complexity.

**Comment by Natooz** [comment]
That was even faster than I imagined, done in #41 and just released in v2.0.6 🙌

**Comment by juancopi81** [comment]
Wow! That's awesome. I'll try to tokenize the LMD clean dataset and share it Hugging Face and here if it is useful for someone :)

**Comment by Natooz** [comment]
You can try what you just did :)
`tokenizer(tokens)` will take care of converting the generated `tokens`. No need for programs here as they are included in the tokens for `MMM`.

**Comment by juancopi81** [comment]
Ah sorry! I thought it was mandatory to add the `get_midi_program` Thanks!
