### ISSUE TITLE
Include additional token for `is_drum` program status

### ISSUE THREAD

**Issue by Kinyugo** [Natooz/MidiTok#42]
Hello, 

Thank you for the amazing library. When including additional tokens for the programs, kindly consider adding a token to indicate whether the program is a drum or not. Let me know if there are other ways to go about or if there is some way to determine these directly from the tokens.

**Comment by Natooz** [comment]
Hi,

Sorry for the late reply.
This is already somehow done. By convention, MidiTok uses the -1 number for drum tracks.

**Comment by Kinyugo** [comment]
Hello,

Thank you for the reply.

Is there a tokenizer that appends the program token by default with the ids? I am not sure how to go about it. Currently, I am prepending the program and a special token indicating whether it's a drum or not. That approach is not working properly.

I would really appreciate you pointing me in the right direction.

Thanks for your time.

**Comment by Natooz** [comment]
Yes, you can use `REMIPlus` which prepend a `Program` token before each note.
For drums, just use `Program_-1`, I think this is the best approach :) (natively done in miditok)

**Comment by Kinyugo** [comment]
Thank you. I will checkout RemiPlus.

**Comment by Kinyugo** [comment]
Hello,

I did checkout RemiPlus. It seems to concatenate all tracks into one long sequence. I am looking for a tokenizer that does something similar to [MMM : Exploring Conditional Multi-Track Music Generation](https://arxiv.org/pdf/2008.06048.pdf)  but keeps each of the tracks separate as opposed to generating one long sequence of concatenated tracks.
