### ISSUE TITLE
TSD: Difference Between 'TimeShift' and 'Rest'

### ISSUE THREAD

**Issue by JLenzy** [Natooz/MidiTok#45]
Hello,
Simple question here but I am wondering what the difference is functionally between timeshift and rest tokens? 

Thanks!

**Comment by Natooz** [comment]
Hi 😃

A rest is just a TimeShift when no note is currently being played, from the offset time of the last note being played to the onset of the next one.

**Comment by JLenzy** [comment]
Thank you! 
So, a few situations I want to highlight to make sure I understand correctly:

When going midi->tokens:
- if a 'note on' is received, then another note is pressed (before last note ends), then it will be: [note on, timeshift, noteon, timeshift, noteoff, ...] 

and for tokens->midi:
- if the tokens are [note-on, timeshift, note-off], then you would place the note off at the same time value as the note on

**Comment by Natooz** [comment]
> if a 'note on' is received, then another note is pressed (before last note ends), then it will be: [note on, timeshift, noteon, timeshift, noteoff, ...]

Yes that's right (except TSD uses Duration tokens and not NoteOff but I think you got this :) )

> if the tokens are [note-on, timeshift, note-off], then you would place the note off at the same time value as the note on

Hum do you refer to the next NoteOn (arriving after the NoteOff) ? In this case yes. Otherwise if you are talking about the first NoteOn, the NoteOff would end the note after the TimeShift's value.

**Comment by JLenzy** [comment]
Hi @Natooz, sorry to be a bit dense but I'm writing the TSD de-tokenizer and want to double a few more things on this topic:

If the config is set to 'Rest': False, then it will use 'TimeShift' as a replacement, for any situations where there is a gap between two notes.
If the config is set to 'Rest': True, then 'TimeShift' tokens will only be used....when two notes are overlapping? Otherwise it will use 'Rest' tokens for any time there is a space between the two notes?

Also:
I have noticed that for TimeShift/Duration tokens there is a format of:
"messagetype_beat.subdiv.granularity"
i.e. Duration_2.0.4
But for Rest tokens I am seeing:
"Rest_beat.subvid" i.e. "Rest_1.0"

Is the above true for all tokenisation methods that use timeshift/duration/rest tokens?

**Comment by JLenzy** [comment]
Hi @Natooz, thank you for taking the time to answer this! All of it is cleared up now, cheers.
