### ISSUE TITLE
MIDI-like tokenizer / detokenizer for music transcription

### ISSUE THREAD

**Issue by WuYiming6526** [Natooz/MidiTok#48]
Hello,

I am trying to tokenize MIDI data for music transcription task, as described in the following works:
[Sequence-to-Sequence Piano Transcription with Transformers](https://arxiv.org/abs/2107.09142)
[MT3: Multi-Task Multitrack Music Transcription](https://arxiv.org/abs/2111.03017)
The tokens in these works are also called "MIDI-like", but unlike the "This time with feeling" paper, they use absolute time shift encoding and "ties" mechanism. Can the MIDI-like tokenizer in MidiTok reproduce the tokenization/detokenization process in MT3?

**Comment by Natooz** [comment]
Hello,

The current implementation does represent time as in Music Transformer, and so does not represent absolute time values.
If you want this feature, I think you can edit the MIDILike class to handle the time that way, it shouldn't be too hard to do.

**Comment by WuYiming6526** [comment]
> If you want this feature, I think you can edit the MIDILike class to handle the time that way, it shouldn't be too hard to do.

I think so, shall I make a PR to add the feature for the MIDILike class?

**Comment by Natooz** [comment]
It might me too niche I think, but thank you for the proposition :)

**Comment by aouzan-k** [comment]
Hello

**Comment by Chunyuan-Li** [comment]
@WuYiming6526 Hello, have you tested the improvement in accuracy/generation performance when attempting to replace the encoding in MT3 with Miditok?
