### ISSUE TITLE
Adding a custom token - Windowing the midi files

### ISSUE THREAD

**Issue by juancopi81** [Natooz/MidiTok#49]
Hi,

Thanks for the great library. I am starting to work with the MMM tokenizer. I'd love to change two things in the tokenizer and before starting doing it, I wanted to check if there's a native way to do it or if you recommend one specific approach:

1. I notice that when tokenizing with MMM the tracks become very long (the size of the whole song). I was wondering about chunking the Midi files before tokenizing them in bars specifying a window_size (total number of bars to take into account for each sample) and a hop_length (the bridge between each window_size). My idea is to have more samples where each track is not that long so the model can see how tracks interact without having a huge context size. For instance, in the tokenize_midi_dataset adding something like:

```py
def chunk_midi(midi, window_size, hop_length, beats_per_bar=4):
    ticks_per_bar = midi.ticks_per_beat * beats_per_bar

    window_size_ticks = window_size * ticks_per_bar
    hop_length_ticks = hop_length * ticks_per_bar

    chunked_midis = []

    for i in range(0, len(midi), hop_length_ticks):
        chunked_midis.append(midi[i:i + window_size_ticks])

    return chunked_midis
```

2. Would it be possible to add a custom token? I'd love to add the genre of the song from the dataset so in inference, the model can be guided by genre.

Thank you very much!

**Comment by Natooz** [comment]
Hey, 

1. I think its a valid option, you might just chunk the MIDI, save the chunks then call `tokenize_midi_dataset` on all of them for instance
2. You can do it manually (I think its the `add_token_to_vocab` or a similar method, I cannot check right now), then add the token to the sequence for instance

**Comment by juancopi81** [comment]
Great! Thanks for your answer :)
