### ISSUE TITLE
Multi voc tokenizers decoding

### ISSUE THREAD

**Issue by Kapitan11** [Natooz/MidiTok#59]
Hey!

I've encountered a problem and would like a second opinion on it. Note that this bug report is concerning the earlier miditok version `2.0.6`.
EDIT: Just checked, on the newest version (`2.1.1`) the problem persists.

Right now I'm doing experiments with Transformer architecture and multi voc tokenizers (CPWord, Octuple and MuMIDI).

On every training epoch end, I'm calling a PyTorch Lightning Callback to generate some samples. Now, when I'm calling `tokens_to_midi()` I've encountered numerous problems.

These issues occurred while using MuMIDI tokenizer:
(Note that, for the processing the data I add PAD_None event to every token if the token length is not the max.)

**1.** If I transform the sequence to `TokSequence` and run `complete_sequence()` and then input it to the `tokens_to_midi()` then I'm getting this issue:

```
    [...]
    full_midi = self.tokenizer.tokens_to_midi(tok_seq_sequence, time_division=384) 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/miditok/midi_tokenizer.py", line 79, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/miditok/tokenizations/mumidi.py", line 413, in tokens_to_midi
    tracks[current_track].append(
    ~~~~~~^^^^^^^^^^^^^^^
KeyError: 0

```

**2.** If I transform the sequence to a list of lists the error is the same as 0.

**3.** I wrote a function to filter out 0 after generation so that it resembles the way the MuMIDI tokenizer outputs the tokens originally (different length depending on the token type).
**3a.** I transform such list of lists to `TokSequence` and run `complete_sequence()` and then input it to the `tokens_to_midi()` similar to 1. I'm getting the same error (the error output is from the notebook though):

```
----> 1 tokenizer.tokens_to_midi(t)

File [...]/python3.11/site-packages/miditok/midi_tokenizer.py:79, in _in_as_seq..decorator..wrapper(*args, **kwargs)
     77 args = list(args)
     78 args[1] = seq
---> 79 return function(*args, **kwargs)

File [...]/python3.11/site-packages/miditok/tokenizations/mumidi.py:413, in MuMIDI.tokens_to_midi(self, tokens, _, output_path, time_division)
    410         vel = int(vel)
    411         duration = self._token_duration_to_ticks(duration, time_division)
--> 413         tracks[current_track].append(
    414             Note(vel, pitch, current_tick, current_tick + duration)
    415         )
    417 # Appends created notes to MIDI object
    418 for program, notes in tracks.items():

KeyError: 0
```
**3b.** I directly input the list of lists (with different lengths) to the `token_to_midi()` function, and I'm getting the following error:

```
----> 1 tokenizer.tokens_to_midi(removed)

File [...]/python3.11/site-packages/miditok/midi_tokenizer.py:78], in _in_as_seq..decorator..wrapper(*args, **kwargs)
     76     else:
     77         for seq_ in seq:
---> 78             self.complete_sequence(seq_)
     80 args = list(args)
     81 args[1] = seq

File [...]/python3.11/site-packages/miditok/midi_tokenizer.py:500], in MIDITokenizer.complete_sequence(self, seq)
    498     seq.tokens = [str(event) for event in seq.events]
    499 elif seq.ids is not None:
--> 500     seq.tokens = self._ids_to_tokens(seq.ids)
    501 elif seq.bytes is not None:
    502     seq.tokens = self._bytes_to_tokens(seq.bytes)

File [...]python3.11/site-packages/miditok/midi_tokenizer.py:552], in MIDITokenizer._ids_to_tokens(self, ids, as_str)
    549     return tokens
    551 for id_ in ids:
--> 552     event_str = self[id_]
    553     tokens.append(event_str if as_str else Event(*event_str.split("_")))
    554 return tokens
...
   1632         else self.__vocab_base_inv
   1633     )
   1634 return voc[item]

TypeError: list indices must be integers or slices, not NoneType
```

Edit: Here is the [example_sequence.zip](https://github.com/Natooz/MidiTok/files/12031069/example_sequence.zip) with the tokenizer parameters to get the error in detokenization.

**Comment by Kapitan11** [comment]
I would gladly appreciate any help in solving this issue!

The attached zip file [detokenize_multivocab_error.zip](https://github.com/Natooz/MidiTok/files/12064127/detokenize_multivocab_error.zip) contains a .ipynb file with examples of errors for each multi-vocab tokenizer, as well as respective params and (generated) sequence that causes the errors.

**Comment by Natooz** [comment]
The last commit (089fa747eed39a22ad899c80ad5dea68d58daeb7) brings a few modifications in the `in_as_seq` decorator (especially handling MuMIDI ids as lists of ints), as well as a few fixes for i/o for the tokens_to_midi and tokens_to_track methods.

The code from my message above still produce errors:

* for MuMIDI because in the tokens a `Pitch / Velocity / Duration` token happens before a `Program` one;
* for CPWord because the token doesn't seem to be well generated, some tokens have 2 or 3 sub-tokens whereas 5 are expected.

For MuMIDI, we can set a default Program in case none is found for the first note. For CPWord I guess you should check again how the tokens are generated in your code.
