### ISSUE TITLE
TimeSignature tokens

### ISSUE THREAD

**Issue by ilya16** [Natooz/MidiTok#64]
Hi, Nathan! I would like to raise the discussion about the implementation of time signature tokens, since I think they are not used much now, but also after seeing you add them to other tokenizations in #62 :)

The current way to build a time signature token vocabulary remains unchanged since #10 and is exhaustive. I suggest a more flexible configuration using a dictionary:

```
{denom_i: num_i / [num_i1, ..., num_in] / (min_num_i, max_num_i)}
```

For each denominator (beat resolution) `denom_i`, a user can specify all supported numerators (bar lengths in beats) using either:
1. a single number `num_i`;
2. a list of all numbers `[num_i1, ..., num_in]`;
3. a range of all numbers in `(min_num_i, max_num_i)`.

Examples:
* The default tine_signature_range for 4/4 will simply be `{4: 4}`.
* 3/4 and 4/4 will be `{4: [3, 4]}`.
* A list of specific (e.g. based on your dataset) time signatures such as 1/2, 2/2, 3/2, 4/2, 2/4, 3/4, 4/4, 5/4, 6/4, 3/8, 6/8, 9/8 will be configured as `{2: (1, 4), 4: (2, 6), 8: [3, 6, 9]}`. With the current configuration using `(8, 2)`, we get 18 redundant time signatures for values like 1/8, 13/8, etc.

I have all the code ready and will file a PR if you like this suggestion. 

The configuration can also be simplified by removing, for example, point 1 and leaving only 2 and 3, it's just I find `{4: [4]}` a bit uglier than `{4: 4}` :)

**Comment by Natooz** [comment]
Hey 👋,

The timing for this discussion couldn't be better :)
Indeed the TS creation hasn't been really changed, and it could be done better.
One reason is that I didn't really used them, and didn't really followed how they are created (`_quantize_time_signatures` and `__create_time_signatures`) and also have some confusion on how do decode its values.

I think your method is indeed clearer and offers good flexibility. You can send the PR.

Also, maybe you input on the denominator decoding could be valuable:
From my understanding of the MIDI protocole,  the time division (nb of ticks per beat) is always consistent across a MIDI. As when decoding MIDI messages we know the exact ticks of the notes ends, we can easily decode their duration in nb of ticks. And as the time division remains the same, the duration in beat is always deduced from it.
I assume then that the TS denominators are purely informative, that we do not need to know what the "note value" is.
Please tell me if I misunderstood anything, and if so how we should handle these values when encoding / decoding tokens.
Currently the TS values are only used in REMI, as we need to consider the number of beats per bar.

**Comment by ilya16** [comment]
@Natooz sorry for taking a while to reply. 

As I understand it, the time division defines the length of the quarter note ("MIDI beat") in ticks, which is used in tempo BPM values that have nothing to do with beats in bars. The beat of the bar is still given by the time signature denominator (note value), and the length of the bar in ticks is calculated as `time_division * 4 * num / denom`. I think that for encoding all metrical structures of a piece, it is important to consider the beat values.

Regarding encoding, I guess it is possible to represent time signature tokens as ratios of 4 quarter note bar lengths, although I cannot recall seeing anything like this anywhere. Another option is to use one token for the number of beats and one for the note value, since we need it to determine the bar length in ticks. The separate encoding of the beat number might help the models learn better, but for large datasets I guess it will not matter.
