### ISSUE TITLE
MIDILike with use_programs=False

### ISSUE THREAD

**Issue by caenopy** [Natooz/MidiTok#68]
Hi, MIDILike with multiple token streams seems to be mishandling time duration tokens. The following should reproduce the issue for any multitrack MIDI file (I'm using 952df587b9fff5adbeb5f40b288fa64b.mid from LakhMIDI).

```from miditok import MIDILike, TokenizerConfig
from miditok.utils import get_midi_programs
from pathlib import Path
from miditoolkit import MidiFile

tokenizer_config_dict = {
    "pitch_range": (0, 127),
    "beat_res": {(0, 12): 8},
    "nb_velocities": 32, 
    "special_tokens": ["PAD", "SOS", "EOS", "MASK"],
    "use_chords": False,
    "use_rests": False,
    "use_tempos": False,
    "use_time_signatures": False, 
    "use_programs": False,
}
config = TokenizerConfig(**tokenizer_config_dict)
tokenizer = MIDILike(config)

midi_path = PATH_TO_MIDI_FILE
mf = MidiFile(midi_path)
mf.dump('pre.mid')
tokens = tokenizer(mf)  
mf_tok = tokenizer.tokens_to_midi(tokens, programs=get_midi_programs(mf), time_division=mf.ticks_per_beat)
mf_tok.dump('tokenized.mid')
```

I noticed in the recent update enabling programs for MIDILike forces tokenizing into a single token stream. Even though General MIDI doesn't enforce each track in a file to have a single program, assuming this is quite common and useful for building multitrack models. Previous implementations I've seen split multitrack MIDI files into one token stream per track, with the program token prepended to the beginning of the stream. Supporting this explicitly may be too opinionated for the library, but at least having the option to enable program tokens in the tokenizer vocabulary and still be able to tokenize a file into multiple token streams would be appreciated (even if the program tokens are not used, as before).

**Comment by caenopy** [comment]
After looking closer, MIDILike works as documented, but the way TimeShifts are encoded differs from [Oore et al.](https://arxiv.org/abs/1808.03715) cited in the docs.

> While the minimal time step is a fixed absolute size (8 ms), the model can
skip forward in time to the next note event. Thus, any time steps that contain
rests or simply hold existing notes can be skipped with a single event. The
largest possible single time shift in our case is 1 second **but time shifts can
be applied consecutively to allow effectively longer shifts**. The combination of
fine quantization and time-shift events helps maintain expressiveness in note
timings while greatly reducing sequence length compared to an uncompressed
representation.

Time shifts currently aren't applied consecutively if the time between notes is larger than the maximum TimeShift event. Is there a reason for this?

**Comment by Natooz** [comment]
Hi, 👋

Indeed now when enabling the program option, the tokenizers will automatically treat all the tracks as a single stream. Our motivation was that the approach is more "natural" and offers an easy and efficient multitrack support, well suited for auto regressive generation. (+ recommending to use BPE to reduce the sequence length and improve results)
I didn't receive demand to re-enable the old way since, but I admit that it offering this possibility can bring more flexibility.
I'll work on this next week. I think I'll add a `one_token_stream_for_programs` option in `TokenizerConfig`, that will be set to True by default, that will allow to have Programs in the vocabulary while treating each track separately. Does this approach suits your needs ?

> Time shifts currently aren't applied consecutively if the time between notes is larger than the maximum TimeShift event. Is there a reason for this?

No, there is no good reason for this actually but only my laziness at the time I implemented this, and totally forgot to handle this (as long rests are quite rare). I'll work on this next week too, it shouldn't be too long to do. :)

Thank you for these concerns!

**Comment by caenopy** [comment]
Thanks! Adding the `one_token_stream_for_programs` option would cover my usage. 

Long rests are quite rare unless you hold onto the track abstraction, then it's pretty common for individual instruments/tracks to not be playing for large portions of a file. Reducing tokens to one stream makes sense given it's what MIDI devices see at the end of the day, but there are a few situations where keeping track structure after tokenizing is desirable. I appreciate the support!

**Comment by Natooz** [comment]
Everything is fixed, `TimeShift` (as well as `Rest`) tokens can now be successive.
I didn't test on the Lakh MIDI you mentioned as I don't have the dataset anymore on my drive and its website is offline, but I see no reason for it to not pass. The tests are passing, they already cover lots of situations.
Would you want to run a test before releasing the next version ? You can also upload MIDIs to test here, and I'll run them.

```Python
from .tests_utils import midis_equals
err = midis_equals(mf, mf_tok)  # list, its len should be 0
```

**Comment by caenopy** [comment]
Thanks! The update fixes parsing the LakhMIDI file on my end.
