### ISSUE TITLE
MIDILike needs note events sorted 

### ISSUE THREAD

**Issue by caenopy** [Natooz/MidiTok#69]
Hi! When disabling `use_chords`, `use_tempos`, and `use_time_signatures`, and attempting to tokenize a file with a single instrument, the `_midi_to_tokens()` method in `midi_tokenizer.py` doesn't sort note events before adding time events:

https://github.com/Natooz/MidiTok/blob/720d707e90705f1e3e55a5bf4350891a05fcbcf9/miditok/midi_tokenizer.py#L582

This causes single track files to be parsed incorrectly with the following config:

```
from miditok import MIDILike, TokenizerConfig
from miditok.utils import get_midi_programs
from pathlib import Path
from miditoolkit import MidiFile

tokenizer_config_dict = {
    "pitch_range": (0, 127),
    "beat_res": {(0, 4): 8, (4, 12): 4},
    "nb_velocities": 32, 
    "special_tokens": ["PAD", "SOS", "EOS", "MASK"],
    "use_chords": False,
    "use_rests": False,
    "use_tempos": False,
    "use_time_signatures": False, 
    "use_programs": False,
}
config = TokenizerConfig(**tokenizer_config_dict)
tokenizer = MIDILike(config)

midi_path = PATH_TO_MIDI_FILE
mf = MidiFile(midi_path)
mf.dump('pre.mid')
tokens = tokenizer(mf)  
mf_tok = tokenizer.tokens_to_midi(tokens, time_division=mf.ticks_per_beat)
mf_tok.dump('tokenized.mid')
```

I'm not sure why sorting note events is disabled in this case, setting the bool to true seems to fix it for me!

You can use `2004/MIDI-Unprocessed_XP_16_R2_2004_01_ORIG_MID--AUDIO_16_R2_2004_02_Track02_wav.midi` from MAESTRO with the above snippet to replicate the behavior.

**Comment by Natooz** [comment]
Thank for the bug report.
`need_to_sort_note_events` has been added to avoid calls to sort methods to speed up the tokenization, assuming the only events are notes already sorted, which was an error from my part

This is fixed in bacea19e70ba596a05fbbcf9f2bf53beb9714540
This will in the next release, as soon as #68 is fixed, hopefully on Monday or Tuesday 🙌
