### ISSUE TITLE
Add ability to add custom labels to DatasetTok

### ISSUE THREAD

**Issue by leleogere** [Natooz/MidiTok#78]
The abstract class `_DatasetABC` allows input labels. However, the `DatasetTok` class doesn't allow that. It would be very handy to be able to specify labels when we want to do other tasks than MIDI generation (classification for example).

**Comment by Natooz** [comment]
Hello 👋

Thank you for the suggestion!
When creating `DatasetTok` I didn't included labels within it as I didn't know exactly how to do it. I assumed if an user needed labels, he would probably subclass `_DatasetABC` to fit its own needs.

Is there a way you have think of to implement labels within `DatasetTok` ?
The first intuitive way I think of would be to read labels that would be included within the json token files. But this would not work when loading MIDI files from the dataset.

The DatasetTok class would become:

```Python
class DatasetTok(_DatasetABC):
    def __init__(
        self,
        files_paths: Sequence[Path],
        min_seq_len: int,
        max_seq_len: int,
        tokenizer: MIDITokenizer = None,
        one_token_stream: bool = True,
        sample_key_name: str = "input_ids",
        labels_key_name: str = None,
    ):
        labels = None if labels_key_name is None else []
        samples = []
        if tokenizer is not None:
            one_token_stream = tokenizer.one_token_stream

        for file_path in tqdm(
            files_paths,
            desc=f"Loading data: {files_paths[0].parent}",
            miniters=int(len(files_paths) / 20),
            maxinterval=480,
        ):
            label = None
            if file_path.suffix in MIDI_FILES_EXTENSIONS:
                midi = MidiFile(file_path)
                for _ in range(len(midi.instruments) - 1):
                    del midi.instruments[1]  # removes all tracks except first one
                tokens = tokenizer.midi_to_tokens(midi)
                if one_token_stream:
                    tokens = tokens.ids
                else:
                    tokens = [seq.ids for seq in tokens]
            else:
                with open(file_path) as json_file:
                    tokens = json.load(json_file)
                    if labels_key_name is not None:
                        label = tokens[labels_key_name]
                    tokens = tokens["ids"]
            if one_token_stream:
                tokens = [tokens]

            # Cut tokens in samples of appropriate length
            for seq in tokens:
                subseqs = split_seq_in_subsequences(seq, min_seq_len, max_seq_len)
                samples += subseqs
                if label is not None:
                    labels += [label] * len(subseqs)

        super().__init__(samples, labels, sample_key_name=sample_key_name, labels_key_name=labels_key_name)
```

**Comment by leleogere** [comment]
Thank you for your comment. In my case, the labels are included in the filename (which might or might not be a good practice, but that's how my dataset is formatted), so I ended up copying DatasetTok but with an additional argument `label_from_filename` that takes a `Callable[[str], str]` and use it to get the label for each file.

However, I am not super happy with it as it creates a lot of redundancy with the original DatasetTok. Having the labels in the json makes sense, but indeed it wouldn't work with midi files. Maybe a function like `label_from_file_path` (`Callable[[Path], str`) would be more versatile as one could extract labels from the complete file path instead of just the name as I did my initial solution?

```py
# when the label is in the filename like "dataset/file1_label=2.mid" the user can use a function like:
def get_label(file_path: Path) -> str:
    return file_path.stem.split("_label=")[1]
dataset = DatasetTok(..., label_from_file_path=get_label)

# when the label is in the parent directory's name like "dataset/label=2/file1.mid" the user could use:
def get_label(file_path: Path) -> str:
    return file_path.parent.name.split("=")[1]
dataset = DatasetTok(..., label_from_file_path=get_label)

# we could even imagine that the labels are stored in another file "labels.csv" in the form "file1.mid,2"
filename_to_label = {}
with open("path/to/labels.csv", "r") as labels:
    lines = labels.readlines()
    for line in lines:
        name,label = line.split(",")
        filename_to_label[name] = label
dataset = DatasetTok(..., label_from_file_path=lambda path: filename_to_label[path.name])
```

**Comment by Natooz** [comment]
I think calling a method to extract the labels could be a good way indeed, as it would offer the user the best flexibility, and work for both json and mid files.
In this case, no need to subclass anything, let's just make `DatasetTok` able to call such `func` function provided by the user.

Now we must think of what positional arguments would be given to the method. I guess we could do :

* .mid file: `label = func(file_path, midi)`
* .json file: `label = func(file_path, tokens)` (with the tokens just being loaded from the json, that could contain labels)

What do you think of this approach ?

**Comment by leleogere** [comment]
I think I was only thinking of passing the `file_path`. Do you think passing the midi/tokens to the function would be useful?

**Comment by Natooz** [comment]
Branch merged, labels (as tensor) should work by installing from git :)
