### ISSUE TITLE
Raise error or warn if same file name in `tokenize_midi_dataset`

### ISSUE THREAD

**Issue by leleogere** [Natooz/MidiTok#79]
Let's say I have a directory structure like the following:
```
data_dir
├── player1
│   ├── recording1.mid
│   ├── recording2.mid
│   ├── recording3.mid
│   └── recording4.mid
└── player2
    ├── recording1.mid
    ├── recording2.mid
    └── recording3.mid
```
And I want to tokenize the files:
```py
data_dir = Path("data_dir")
midi_files = list(data_dir.glob('**/*.mid'))
# > pprint(midi_files)
# [PosixPath('data_dir/player1/recording2.mid'),
#  PosixPath('data_dir/player1/recording4.mid'),
#  PosixPath('data_dir/player1/recording1.mid'),
#  PosixPath('data_dir/player1/recording3.mid'),
#  PosixPath('data_dir/player2/recording2.mid'),
#  PosixPath('data_dir/player2/recording1.mid'),
#  PosixPath('data_dir/player2/recording3.mid')]
tokenizer.tokenize_midi_dataset(midi_paths, Path("tokenized"))
```
Then tokenized will only have the following structure:
```
tokenized
├── recording1.json
├── recording2.json
├── recording3.json
└── recording4.json
```
Half of the files are overwritten without warning because they have the same filename.

The ideal would be to recreate the same tree structure as the initial midi files (but that would require having a single `Path` in argument rather than `list[Path]`). If that's too complex, I think that it should raise an error, or at the very least print a warning saying that some files have the same name and that only one of them will be present in the output directory.

**Comment by Natooz** [comment]
Thank you for this report!
Indeed this can be problematic and should be worked on. I was already aware that the current way of dealing with file paths was not ideal, but tbh have been lazy as of right now.

I think reproducing the file tree / structure would be best. In this case, this would require to either:

1. have the root directory of the tree given by the user as argument (`root_directory`);
2. guess the root, by analysing all the paths and find the deepest common directory;
3. the user doesn't provide a list of paths of files to tokenize, but a path leading to a directory, we can recursively find the files and we have the root.

Cases 1 and 3 would be easy to handle. For case 2, I think we should provide an additional option (as argument) `guess_root_directory` to let the user decide wether to find the root and reproduce the tree, or to put all the files in a unique directory (as of right now). If the user doesn't provide `root_directory` and `guess_ root_directory` is False, then we put everything in `out_dir`, and when writing a file, we check if it already exists. If that's the case, the name of the current file to write is prepended by its parent directory name.

What do you think of this of this approach ?

**Comment by leleogere** [comment]
I think it would be nice. I am not sure about the `guess_root_directory`, I feel like it's a little clucky... I think most people could live with:
- providing a root directory, then the directory is scanned for the list of matching files and the structure is copied in the output (however what do we do if there is both `json` and `mid` files in there?)
- providing a list of files, in which case we could analyse the deepest common directory and prepend the full path to the filename (because with only the parent directory, we could face another same-name issue). However, that could result in possibly very long names...

**Comment by Natooz** [comment]
Before calling the method, the `output_dir` should in theory be empty. It is after all the directory the user will use to store token files essentially. We could add an option to overwrite files that already exist or append a number to the name of the current file to save, but although I don't think this should happen (maybe someone trying to tokenize several MIDI datasets into one common directory, with overlapping file names / trees ?).

Now for the tree in case `midi_paths` is a list of files: I don't think adding the parents directory in the name is a good idea. But we can easily reproduce the tree up to the deepest common parent directory (of all `midi_paths`) within `out_dir`. This seems like a more reasonable option imho. And so in this case, it will systematically reproduce the tree structure (unless we allow to explicitly not with say a `guess_root_directory` or `dont_reproduce_file_tree` argument)
