### ISSUE TITLE
Duration augmentation not implemented in `data_augmentation_midi`

### ISSUE THREAD

**Issue by leleogere** [Natooz/MidiTok#85]
In the function `data_augmentation_midi`, the duration augmentation is not implemented (it is commented). It means that if one tries to call the function with only `duration_offsets` as parameters, the result of the function will only be an empty list.
https://github.com/Natooz/MidiTok/blob/ed0d500603b69f34c4654f5db0037e4f3aed45ff/miditok/data_augmentation/data_augmentation.py#L381-L404

I think that as long as this is not implemented, the parameter should be removed, or it should be specified in the doc and raise an exception when used so people wouldn't be surprised by the result.

**Comment by Natooz** [comment]
Indeed. For now, I'll add a warning and a note in the documentation.
At least, the feature should be done in the future. It will however need some thoughts on how to compute the offsets (the reason why I didn't finish it at the time)

**Comment by leleogere** [comment]
Perfect! Does it work in `data_augmentation_tokens` tho?

**Comment by Natooz** [comment]
Yes it does work for tokens. :)
The token implementation is more straightforward and rapid, it works by increasing/decreasing duration token ids, corresponding to the adjacent values.
Data augmentation is faster when performed on tokens.

**Comment by leleogere** [comment]
By the way, I'm not really sure what duration augmentation means. Is it supposed to augment the duration of each note, without changing their starting time? Or is it supposed to augment the duration AND shift the starting time of all the following notes? (which would result in slower/faster tracks)

**Comment by Natooz** [comment]
It only increase the duration of the notes, not their starting/onset times. No starting time is shifted, so the notes are not played faster or slower.
I'll also include this in the doc (in #82 for simplicity) shortly ! :)
