### ISSUE TITLE
ERROR:model.generate(input_tokens.ids, max_length=200)-------AttributeError: 'list' object has no attribute 'ids'

### ISSUE THREAD

**Issue by geng-lee** [Natooz/MidiTok#86]
How to fix it?

generated_token_ids = model.generate(input_tokens.ids, max_length=200)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-19-3ba976a250e8>](https://localhost:8080/#) in <cell line: 12>()
     10 input_tokens = tokenizer(input_midi)
     11 
---> 12 generated_token_ids = model.generate(input_tokens.ids, max_length=200)
     13 # generated_midi = tokenizer(generated_token_ids)
     14 # generated_midi.dump("/content/out/continued.mid")

AttributeError: 'list' object has no attribute 'ids'

**Comment by leleogere** [comment]
Maybe try with `model.generate(input_tokens[0].ids, max_length=200)`

**Comment by geng-lee** [comment]
[leleogere](https://github.com/leleogere) Thanks! but, it doesn't work

> Maybe try with `model.generate(input_tokens[0].ids, max_length=200)`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-26-2ef1cef5db42>](https://localhost:8080/#) in <cell line: 17>()
     15 # input_tokens = input_tokens['input_ids']
     16 # input_tokens = np.array(input_tokens[0].ids)
---> 17 generated_token_ids = model.generate(input_tokens[0].ids, max_length=200)
     18 # generated_midi = tokenizer(generated_token_ids)
     19 # generated_midi.dump("/content/out/continued.mid")

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py](https://localhost:8080/#) in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1457             inputs, generation_config.bos_token_id, model_kwargs
   1458         )
-> 1459         batch_size = inputs_tensor.shape[0]
   1460 
   1461         # 4. Define other model kwargs

AttributeError: 'list' object has no attribute 'shape'

**Comment by elloza** [comment]
Same here:
https://github.com/Natooz/BPE-Symbolic-Music/issues/2
