### ISSUE TITLE
Please check your two notebook demos, there are too many errors inside.

### ISSUE THREAD

**Issue by oiabtt** [Natooz/MidiTok#88]
Please run it yourself to check if it can run successfully, especially in the notebook "Full_Example_HuggingFace_GPT2_Transformer.ipynb". In the "Generate music" module, the line "tokens = [seq.tolist() for seq in tokens]" is causing an AttributeError: 'str' object has no attribute 'tolist'.

**Comment by Natooz** [comment]
Hi, thank you for reporting it!
It's fixed in #87 which will be merged soon!
